platform :ios, '7.0'
platform :ios, '8.0'
pod 'Masonry'
pod "SVProgressHUD"
pod 'SDWebImage', '~>3.8'
pod 'YYKit'
pod 'MJRefresh'
pod 'MJExtension'
pod 'ZFPlayer’
pod "DACircularProgress"
target 'XQQThinkProj' do
pod 'AFNetworking', '~> 3.0'
end
